<?php

/**
 * PluginCmsPageTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCmsPageTable extends Doctrine_Table
{
  /**
  * Returns an instance of this class.
  *
  * @return PluginCmsPageTable The table instance
  */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginCmsPage');
  }

  public static function findByIdentifier($identifier) {
    if (empty($identifier) || !is_string($identifier)) {
      throw new Exception("Empty or not string identifier.", 500);
    }
    return Doctrine_Core::getTable('CmsPage')->findOneByIdentifierAndPublished($identifier,1);
  }

  public static function findByIdentifiers($identifiers = array()) {
    if (empty($identifiers) || !is_array($identifiers)) {
      throw new Exception("Empty or not array of identifiers.", 500);
    }

    $pages = Doctrine_Core::getTable('CmsPage')
      ->createQuery('p')
      ->whereIn('p.identifier',$identifiers)
      ->andWhere('p.published = 1')
      ->execute();

    $return = array();

    foreach ($pages as $p) {
      $return[$p->getIdentifier()] = $p;
    }

    return $return;
  }

}